version: "3"

services:
  app:
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:nodejsdeployaws.com.br

  reverse-proxy:
    image: traefik:v1.7
    container_name: traefik-reverse-proxy
    command: --api --docker.exposedbydefault=false
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

